workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - when: never

stages:
  - validate
  - build
  - test
  - security
  - privacy
  - publish

variables:
  IVR_EXECUTION_MODE: "MOCK"
  IVR_INTERNAL_SERVICE_TOKEN: "ci-mock-internal-service-token"
  SALES_PROVIDER: "FAKE_TARGET_V1"
  SIM_PROVIDER: "MOCK"
  REAL_CUSTOMER_CALL_ALLOWED: "NO"
  API_DOCS_PUBLISH_NONPROD: "NO"
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_NOLOGO: "true"
  NUGET_PACKAGES: "$CI_PROJECT_DIR/.nuget/packages"
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

default:
  tags:
    - ginsengfood-docker
  interruptible: true
  retry:
    max: 1
    when:
      - runner_system_failure

include:
  - local: "/deploy/ci/ci.gitlab-ci.yml"
  - local: "/deploy/ci/docs.gitlab-ci.yml"
  - local: "/deploy/ci/contract-e2e.gitlab-ci.yml"
  - local: "/deploy/ci/quality-gate.gitlab-ci.yml"
  - local: "/deploy/ci/ui-qa.gitlab-ci.yml"
  - local: "/deploy/ci/observability.gitlab-ci.yml"
  - local: "/deploy/ci/chaos.gitlab-ci.yml"
  - local: "/deploy/ci/registry.gitlab-ci.yml"
