// W-0054 / P10-3 — SIM pool sizing from the peak, not the average.
//
// The number this produces is a MODEL. It has never been calibrated against a real dial, because
// no real dial has happened (W-0008). What it does is make the arithmetic explicit and checkable,
// so that when the lab produces measurements the model can be corrected rather than replaced.
//
// The core mistake this exists to avoid: sizing from daily average. Golden Hour concentrates its
// entire attempt window into minutes, so a pool that comfortably handles the daily mean will miss
// deadlines every morning and expire orders that were never unreachable.

/** DT-04: one channel carries one active call, and pauses between calls. */
export const CHANNEL_CONSTRAINTS = {
  oneCallPerChannel: true,
  cooldownSeconds: 5,
};

/**
 * W-0132 — the one place that says how long a call is assumed to take.
 *
 * Three numbers were living independently, and nothing compared them:
 *
 *   40s + 5s cooldown  this model and its self-test
 *   50s                implied by spec §23 M8-P0-009, which sizes 32 SIM at ~192 calls per
 *                      five-minute window (32 x floor(300 / 50) = 192)
 *   60s                SchedulerOptions.ExpectedCallDurationSeconds, the runtime default
 *
 * They are NOT unified here, and unifying them is not a code decision. Picking one number means
 * claiming a measured call duration, and no call has been dialled (W-0008). What this constant
 * does is make the disagreement declared instead of accidental, so CAP-DRIFT-05 can fail the
 * moment any of the three moves without the others being reconsidered.
 *
 * When W-0008 produces a measurement: set the measured value, flip `calibrated`, and point
 * `calibratedBy` at the evidence. CAP-DRIFT-05 will then require the three to agree.
 */
export const CALL_DURATION_ASSUMPTIONS = {
  calibrated: false,
  calibratedBy: null,
  calibrationWork: "W-0008",

  /** What this model and its self-test assume. */
  modelCallSeconds: 40,

  /** Implied by spec §23 M8-P0-009: 32 SIM serving ~192 calls in a 300s window. */
  specConservativeSeconds: 50,

  /** SchedulerOptions.ExpectedCallDurationSeconds default in SchedulerCapacity.cs. */
  schedulerDefaultSeconds: 60,
};

/**
 * Candidate attempt policies. MOCK/LAB only — the production policy is unsigned (W-0007), and the
 * model takes a policy as input precisely so that signing a different one does not require
 * touching this file.
 */
export const CANDIDATE_POLICIES = {
  GOLDEN_HOUR: { windowSeconds: 300, offsetsSeconds: [0, 150], maxAttempts: 2 },
  TWENTY_FOUR_SEVEN: { windowSeconds: 900, offsetsSeconds: [0, 450], maxAttempts: 2 },
};

/**
 * Channels needed to clear `attempts` dials inside `windowSeconds`.
 *
 * Each channel can serve floor(window / (duration + cooldown)) calls in the window. The ceiling of
 * attempts over that is the pool. Two properties worth naming:
 *
 *   - cooldown is inside the divisor, not subtracted at the end. A five-second pause after a
 *     forty-second call costs 11% of the channel's capacity, every call, not once.
 *   - the result is a ceiling. Half a channel cannot take a call, and rounding down here is the
 *     arithmetic that produces a pool which is correct on paper and short in practice.
 */
export function channelsForWindow({ attempts, windowSeconds, callSeconds, cooldownSeconds }) {
  if (attempts <= 0) {
    return 0;
  }
  const perCallSeconds = callSeconds + cooldownSeconds;
  const callsPerChannel = Math.floor(windowSeconds / perCallSeconds);
  if (callsPerChannel <= 0) {
    // A single call does not fit in the window. No pool size fixes that; the policy or the call
    // duration has to change, and returning a huge number would hide a design error as a
    // procurement problem.
    return Number.POSITIVE_INFINITY;
  }
  return Math.ceil(attempts / callsPerChannel);
}

/**
 * Attempts generated by `orders` orders, given a no-answer rate that sends some of them to a
 * second attempt inside the same window.
 *
 * Only counted customer attempts (DT-02). A technical retry re-uses the same attempt number and
 * must not inflate the pool, or the model sizes for a failure mode instead of for demand.
 */
export function attemptsFor({ orders, noAnswerRate, maxAttempts }) {
  let attempts = orders;
  let carried = orders;
  for (let attempt = 2; attempt <= maxAttempts; attempt++) {
    carried = carried * noAnswerRate;
    attempts += carried;
  }
  return attempts;
}

/**
 * Pool for one programme at peak.
 *
 * `peakShare` is the fraction of the day's orders that arrive in the busiest window. For Golden
 * Hour this is the whole point: the programme exists to call people in the minutes after they
 * order, so the arrival pattern follows the shop's traffic and not a flat day.
 */
export function poolForProgramme({
  dailyOrders,
  eligibleRate,
  peakShare,
  noAnswerRate,
  callSeconds,
  policy,
}) {
  const eligible = dailyOrders * eligibleRate;
  const peakOrders = eligible * peakShare;
  const attempts = attemptsFor({
    orders: peakOrders,
    noAnswerRate,
    maxAttempts: policy.maxAttempts,
  });

  return {
    eligible,
    peakOrders,
    attempts,
    channels: channelsForWindow({
      attempts,
      windowSeconds: policy.windowSeconds,
      callSeconds,
      cooldownSeconds: CHANNEL_CONSTRAINTS.cooldownSeconds,
    }),
  };
}

/**
 * Total pool across programmes.
 *
 * Summed, not maximised. The two programmes overlap in time — a 24/7 COD order placed at 09:00 is
 * being called during the same minutes as the Golden Hour peak — and taking the maximum would
 * assume they take turns.
 */
export function poolForDay(scenario) {
  const perProgramme = Object.entries(scenario.programmes).map(([name, programme]) => [
    name,
    poolForProgramme({
      dailyOrders: scenario.dailyOrders * programme.share,
      eligibleRate: scenario.eligibleRate,
      peakShare: programme.peakShare,
      noAnswerRate: scenario.noAnswerRate,
      callSeconds: scenario.callSeconds,
      policy: programme.policy,
    }),
  ]);

  const channels = perProgramme.reduce((total, [, result]) => total + result.channels, 0);
  return { perProgramme: Object.fromEntries(perProgramme), channels };
}

/**
 * Sensitivity sweep. Returns the pool at each corner of the input ranges, so the answer is an
 * interval rather than a point.
 *
 * A single number invites a procurement decision it cannot support: every input here is an
 * assumption nobody has measured, and the honest output of unmeasured inputs is a range plus the
 * name of the input that moves it most.
 */
export function sweep(base, ranges) {
  const keys = Object.keys(ranges);
  const results = [];

  const walk = (index, scenario) => {
    if (index === keys.length) {
      results.push({
        inputs: Object.fromEntries(keys.map((key) => [key, scenario[key]])),
        channels: poolForDay(scenario).channels,
      });
      return;
    }
    for (const value of ranges[keys[index]]) {
      walk(index + 1, { ...scenario, [keys[index]]: value });
    }
  };
  walk(0, base);

  const channels = results.map((result) => result.channels);
  return {
    results,
    minimum: Math.min(...channels),
    maximum: Math.max(...channels),
    // Which input moves the answer most, measured rather than asserted. This is what a reader
    // should go and measure first in the lab.
    dominant: keys
      .map((key) => {
        const byValue = new Map();
        for (const result of results) {
          const bucket = byValue.get(result.inputs[key]) ?? [];
          bucket.push(result.channels);
          byValue.set(result.inputs[key], bucket);
        }
        const means = [...byValue.values()].map(
          (bucket) => bucket.reduce((sum, value) => sum + value, 0) / bucket.length);
        return { input: key, spread: Math.max(...means) - Math.min(...means) };
      })
      .sort((a, b) => b.spread - a.spread)[0],
  };
}

/**
 * The scenario the documents quote. Every number is an ASSUMPTION with no measurement behind it —
 * business volume is an owner input that has not arrived, and call duration has never been
 * observed because no call has been placed.
 */
export const UNCALIBRATED_SCENARIO = {
  dailyOrders: 2_000,
  eligibleRate: 0.6,
  noAnswerRate: 0.3,
  callSeconds: CALL_DURATION_ASSUMPTIONS.modelCallSeconds,
  programmes: {
    GOLDEN_HOUR: {
      share: 0.4,
      // The whole daily Golden Hour volume does not arrive at once; this is the busiest window's
      // share of that programme's day.
      peakShare: 0.15,
      policy: CANDIDATE_POLICIES.GOLDEN_HOUR,
    },
    TWENTY_FOUR_SEVEN: {
      share: 0.6,
      peakShare: 0.1,
      policy: CANDIDATE_POLICIES.TWENTY_FOUR_SEVEN,
    },
  },
};

/** Monthly cost. Rates are placeholders: no vendor quote exists (W-0008). */
export function monthlyCost({ channels, simMonthlyCost, gatewayMonthlyCost, infraMonthlyCost }) {
  return (channels * simMonthlyCost) + gatewayMonthlyCost + infraMonthlyCost;
}

/**
 * Cost per confirmed order.
 *
 * Divides by CONFIRMED orders, not by calls. A pool that calls twice as often and confirms the
 * same number of orders costs twice as much per outcome, and dividing by calls would hide exactly
 * that.
 */
export function costPerConfirmedOrder({ monthly, confirmedOrdersPerMonth }) {
  return confirmedOrdersPerMonth === 0 ? null : monthly / confirmedOrdersPerMonth;
}
